### ISSUE TITLE
Matchmaking erweiterungen

### ISSUE THREAD

**Issue by TheR00st3r** [Lan2Play/eventula-manager#108]
- Anzeige x/y Spieler beim Team
- Beim Match anlegen den Status direkt auf Offen setzen (bisher werden auch Draft Matches schon bei den Verfügbaren Teams angezeigt)
- Liveupdate der Teams
- Direktes Team wechseln in Oberfläche ermöglichen
- Darstellung der Buttons/Textfields ist unterschiedlich breit
![image](https://user-images.githubusercontent.com/1764864/101212679-6e09a280-3679-11eb-8422-9406c666f669.png)
- Invite Link wird für Team Owner nicht angezeigt

**Comment by Apfelwurm** [comment]
fixed in https://github.com/Lan2Play/eventula-manager/commit/cccb1846c9312a8579e5a911aa86fb92395c4ff7 and autoreload here: https://github.com/Lan2Play/eventula-manager/issues/110
