### ISSUE TITLE
Add event type

### ISSUE THREAD

**Issue by Apfelwurm** [Lan2Play/eventula-manager#158]
Add event type to enable different features for an event.

for example:
- lan-party
- sports
- hackathon

**Comment by th0rn0** [comment]
are you suggestion we extend the scope of the lan manager to more than just gaming events?

I've already looked into this and there is functionality there for it. But the limitations is that one org can only have one event type. This can be looked into though.

**Comment by Apfelwurm** [comment]
> are you suggestion we extend the scope of the lan manager to more than just gaming events?
> 
> I've already looked into this and there is functionality there for it. But the limitations is that one org can only have one event type. This can be looked into though.

jep but we thought about different event types to enable different features within the event. Also because we have currently implemented a checkbox for online event, which leads to a different handling of for example the tournament registration. 
So it would be nice to choose between 

- lan
- wan
- sports
- hackathon (in the future, see #161 if we decide to)

and maybe other types if we implement more event specific features.

**Comment by Apfelwurm** [comment]
out of scope, wont be implemented
