### ISSUE TITLE
admin menu seating plan bricks after setting a seat to inactive

### ISSUE THREAD

**Issue by Apfelwurm** [Lan2Play/eventula-manager#209]
admin menu seating plan bricks after setting a seat to inactive. Workaround is to seat a user on his seat

**Comment by Keulerix** [comment]
Logic in show.blade for admin events lead to taking the status of latest seat in DB, due to foreach loop. But iteration over all seats is unecessary at this point since the needed seat is known at this point. Should be fixed now, but needs testing.

**Comment by Apfelwurm** [comment]
should be fixed
