### ISSUE TITLE
Shared Hosting

### ISSUE THREAD

**Issue by mazzorini** [Lan2Play/eventula-manager#292]
Hi,

any plans for a shared hosting version?

**Comment by Apfelwurm** [comment]
Hi @mazzorini , 
we (lan2play) don't plan to do a hosted version of eventula.
Th0rn0 had plans to reenable his hosting service (but i don't know if thats still the case), but if our changes will be ever merged, i think it will take a long time until then.

Do you have Discord? If thats the case, please go ahead and message me there (Apfelwurm#5627) and i'm sure we can figure something out for you, no matter how the solution might look like.
