### ISSUE TITLE
Mailing not working

### ISSUE THREAD

**Issue by mitSalami** [Lan2Play/eventula-manager#362]
The .env is correctly configured and the container is able to send Mails via curl.
But I still always get a "530 5.7.1 Authentication required". 

Full Error Message:
`[2022-11-17 11:20:05] production.ERROR: Expected response code "250" but got code "530", with message "530 5.7.1 Authentication required". {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 530): Expected response code \"250\" but got code \"530\", with message \"530 5.7.1 Authentication required\". at /web/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:316)
[stacktrace]
#0 /web/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(180): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->assertResponseCode()
#1 /web/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php(105): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->executeCommand()
#2 /web/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(237): Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport->executeCommand()
#3 /web/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(197): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doMailFromCommand()
#4 /web/html/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->doSend()
#5 /web/html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#6 /web/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(521): Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport->send()
#7 /web/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(285): Illuminate\\Mail\\Mailer->sendSymfonyMessage()
#8 /web/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(211): Illuminate\\Mail\\Mailer->send()
#9 /web/html/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Mail\\Mailable->Illuminate\\Mail\\{closure}()
#10 /web/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(212): Illuminate\\Mail\\Mailable->withLocale()
#11 /web/html/vendor/laravel/framework/src/Illuminate/Mail/SendQueuedMailable.php(66): Illuminate\\Mail\\Mailable->send()
#12 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Mail\\SendQueuedMailable->handle()
#13 /web/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#15 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#16 /web/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#17 /web/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#18 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#19 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /web/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#21 /web/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(124): Illuminate\\Bus\\Dispatcher->dispatchNow()
#22 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#23 /web/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /web/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(126): Illuminate\\Pipeline\\Pipeline->then()
#25 /web/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#26 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#27 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#28 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#29 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#30 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#31 /web/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#32 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#33 /web/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#35 /web/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#36 /web/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#37 /web/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(178): Illuminate\\Container\\Container->call()
#38 /web/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#39 /web/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(148): Symfony\\Component\\Console\\Command\\Command->run()
#40 /web/html/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run()
#41 /web/html/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#42 /web/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#43 /web/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(111): Symfony\\Component\\Console\\Application->run()
#44 /web/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#45 /web/html/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#46 {main}
"} 
`

**Comment by Apfelwurm** [comment]
Hey, Eventula uses the default laravel mailing mechanism for sending the mails, there is no special stuff implemented around it.  I need a little bit more infos to analyze your problem, because we have several instances where everything works as expected.

Which Mail settings (driver, mail provider, encryption and port) do you use?

**Comment by Apfelwurm** [comment]
okay, so you have maybe not setted the thing up the right way. I have to invest time into the docs to make them right. Going to tackle that soon, since the readme and the docs are wrong or not complete. Which way did you set up eventula? 

If you use tls, most likeley you want to use port 587 insted of 25 or 2525

Do you have discord? because no matter if you get this to work like its intended, you  going to need help from me to set everything up currently, since, like i mentioned, the docs and the readme is not right at the moment.

**Comment by Apfelwurm** [comment]
please use just the https://github.com/Lan2Play/eventula-manager/blob/master/docker-compose.yml with the env  https://github.com/Lan2Play/eventula-manager/blob/master/.env.example unless you want to run it for developing

**Comment by mitSalami** [comment]
my discord is mitSalami#1363.
