### ISSUE TITLE
Add a switch to the event for staff tournament participation

### ISSUE THREAD

**Issue by Apfelwurm** [Lan2Play/eventula-manager#416]
We need to add a property on the event to set wheter a staff ticket can participate on tournaments. Then we have to adjust setActiveEventParticipant in the users model to that.

**Comment by Mawiguk0** [comment]
There are two quite resonable to use fields in the EventParticipant
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/b5e51321-bbe6-4201-870a-1c9b1f56d2d8)
I would use these and in the event simply two isAllowed fields

**Comment by Mawiguk0** [comment]
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/e800aea1-9e16-45cd-aa38-14681254a698)

**Comment by Mawiguk0** [comment]
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/04bf4a8d-7035-402b-9a89-9e750158f92b)

![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/703b6583-91d2-42d9-ac7e-4621f2c8e5d1)
