### ISSUE TITLE
Signed In Freebie User cant view Details during Event

### ISSUE THREAD

**Issue by Mawiguk0** [Lan2Play/eventula-manager#528]
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/77806016-30f7-4b45-8f22-6a671e79330d)
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/fb77bf44-ea3e-4789-b897-4b79d6a01ae9)

We just need to add another condition other than success here
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/fc27da90-54f4-464e-a608-ff36e68d4e4e)
/web/html/app/Http/Controllers/Events/EventsController.php:51
                    && $participant->purchase->status == "Success"

To accept "Freebie"

and also set the Status to "Freebie", when assigning a Freebie Ticket to the user.

**Comment by Apfelwurm** [comment]
Maybe we can also tackle #416 when there is additional fixing on the tournament stuff required for the freebie users, but thats optional ofc :)

**Comment by Mawiguk0** [comment]
This is also fixed:
![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/4ae8ba77-a4ca-44f3-9df2-a4bad8c6ca70)

![image](https://github.com/Lan2Play/eventula-manager/assets/17619897/a1e8b07f-dddb-4bd3-88d2-6f5bc23c1d9d)
