### ISSUE TITLE
Team Verlassen  löscht team nicht vollständig

### ISSUE THREAD

**Issue by 4ipalino** [Lan2Play/eventula-manager#60]
Das Team wird aus Challonge gelöscht aber nicht aus eventula

**Comment by Apfelwurm** [comment]
Haben wir hier eine Möglichkeit das nachzustellen?

**Comment by 4ipalino** [comment]
Nicht das ich wüsste

**Comment by 4ipalino** [comment]
Kann momentan nicht reproduziert werden
