### ISSUE TITLE
PDF Ticket

### ISSUE THREAD

**Issue by icewindow** [Lan2Play/eventula-manager#614]
## Issue Description

In addition to the standard QR code, a PDF should be generated when a user buys a ticket. The PDF should include basic event information, information about the bought ticket, and the QR code for sign-in.

## Motivation

A PDF can be downloaded by the user and either saved to a mobile device or printed out, so there is no need to have access to the user profile at the time of signing in to the event.  
Additionally, having multiple QR codes on the profile page can be confusing for both the user and event staff. A PDF with the QR code embedded would provide the same functionality but with greatly improved usability, mostly for event staff, as there is only one code to scan per document.

### What information should be included in the PDF?

The PDF could be used just as a carrier for the QR code and some minimal extra information, like identifying personal information (i. e. username, first name, last name, etc).  
Alternatively, the PDF could be used to give instructions to the user, like venue information, things to bring for during the event, terms and conditions, etc. The most important information, mentioned above, should be on the first page of the document.

The best course of action is probably to have the basic information be always present, and additional information can be filled in from either the event or possibly the global site settings.

### Dynamic information

Attached to the ticket are some dynamic information, namely the chosen/assigned seat. Should this information be included in the PDF? If so, how should changes to that information be handled?

### Admin settings

Which settings do admins need to control for the PDF? Is a separate menu needed for those settings or can they be accommodated in already existing forms?

### Changes to static data when PDFs have already been generated

What should happen if any of the underlying data of the PDF change (personal information changed, event info changed, etc.)? In case of user-specific data, the PDF could just be regenerated with the updated data. But changing information which is pulled from the event and/or site settings could potentially cause dozens or hundreds of PDF files to be needed to be regenerated. How should that be handled?

### Used library

Are there any restrictions on usable libraries? Or is anything on public composer repositories like packagist okay to use?

## Possible implementation

The basic form of a PDF should be generated at the same time the QR code for a purchase is generated, as the intention is to include the QR code in the PDF. Generating both the QR code and PDF in the same step would be the most logical. The PDF should be rendered and stored in the same fashion the image for the QR code is stored. A database entry with the path to the PDF file will then also be needed in the `event_participants` table.

Should any sort of dynamic data be chosen to be added to the PDF then there needs to be a route to access the PDF rather than just a plain file download. The route should check if the data has changed and if it has the PDF should be regenerated. In both cases (data changed and unchanged) the PDF should be served to the user.

**Comment by Keulerix** [comment]
First of all nice issue with much details. Thank you! 👍 

I think the only reason to store PDFs in the database would be, if there is some legal or economical reason (Section 6 GDPR) to safe them over a longer period of time. Does anyone has the kind of size, that this might be a consideration?

Since this would also mean that we would have to look at implementing a customizable retention and/or archive solution (even when only talking making the PDF available over an API for such systems), aswell as a role based acces system which can accomodate auditor roles, I don't think this is needed at the moment.

Generating on-the-fly should suffice without storing. What could be considered I think, is to be able to expose this as an opt-in toggled API as well, in case it needs to be called from outside applications, like for example the entrance client.

And even if some organizations that use eventula have these requirements, it may make more sense, to expose APIs and the organizations than have to deploy content servers with retention/archive functions for those needs I think.

**Comment by icewindow** [comment]
I imagined the PDF would be stored as a file alongside the image with the QR code, since they basically fulfill the same purpose. But you raise a valid point, depending on what kind of information is included in the PDF we might need to implement protection against unauthorized access. Role-based access could work, though realistically the only person who should need to access this file is the user themselves, or am I missing something? Maybe we could get away with just using a nonce?
In any case, the PDF would have to be requested via a route, though that option is probably the best anyways.

I'd need to check out what kind of overhead generating a PDF would be vs. just outputting HTML on any other regular site. If the overhead is small enough then generating on the fly might actually be the best solution. That would also allow easy inclusion of dynamic data like seat number.  

I haven't considered API access, since I wasn't aware that Eventula even offered any APIs. What do you mean with "opt-in toggled API"? Simply that the PDF would be an API feature that may or may not be accessible, depending on what the site owner needs?
