### ISSUE TITLE
Add SteamID into UserProfile - Tournament as option required

### ISSUE THREAD

**Issue by Toutzn** [Lan2Play/eventula-manager#646]
For Tournament it will be nice to add SteamID Field for User and an options for requirement.
Because if we start a match, only registered Users with steamID needs to be get access to the server and will be moved to the right Team (get5 does do that ->  https://github.com/PhlexPlexico/G5V)

**Comment by Apfelwurm** [comment]
This is already implemented. As soon as you select the get5 or pugsharp matchapihandler, the prerequirement for the steamid will be checked. You have to use steam authentication for your users.

**Comment by Toutzn** [comment]
Thanks for answer
