### ISSUE TITLE
Coudnt find IP-Adress Docker

### ISSUE THREAD

**Issue by Mrciller** [Lan2Play/eventula-manager#714]
Hello i wanted to install it over docker compose and followed the guide but when i want to start i get the error 
"eventula_manager_loadbalancer  | 2024-06-22T23:47:54+02:00 ERR error="service \"myservice\" error: unable to find the IP address for the container \"/eventula_manager_app\": the server is ignored" container=app-lan-a3ed8ee32825ff1616ad4b979fc07d2097dacaacfe6fdc47bd22f33385f3d145 providerName=docker"

please help, i may not be the smartest

**Comment by Apfelwurm** [comment]
@Mrciller if this is still relevant, please reopen the PR or get on our discord for help. Since this is not an issue with the code, but with your setup, i'm going to close this for now :)
