### ISSUE TITLE
Add Match Unknown Column

### ISSUE THREAD

**Issue by 4ipalino** [Lan2Play/eventula-manager#91]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'team_count' in 'field list' (SQL: insert into `matchmaking` (`game_id`, `status`, `ispublic`, `team_size`, `team_count`, `owner_id`, `invite_tag`, `updated_at`, `created_at`) values (4, DRAFT, 1, 5, 2, 3, 1scsrg3p0hz1, 2020-11-19 21:13:33, 2020-11-19 21:13:33))

**Comment by Apfelwurm** [comment]
das müsste dran liegen dass ich wohl noch eine änderung in der 2020_11_02_015607_create_matchmaking_table.php migration gemacht hab ohne zu bedenken dass du schon gepulled hattest :/ 

Fix mit:

`make database-command command="delete from migrations where migration='2020_11_02_015608_create_matchmaking_teams_table';delete from migrations where migration='2020_11_02_015609_create_matchmaking_team_players_table';delete from migrations where migration='2020_11_02_015607_create_matchmaking_table';delete from migrations where migration='2020_11_16_184728_create_match_making_server_table';"; make database-command command=" drop table matchmaking_team_players; drop table matchmaking_teams;drop table matchmaking_server;drop table matchmaking;";make database-migrate
`
