### ISSUE TITLE
Add option to disable/enable the "None" game selection from matchmaking.

### ISSUE THREAD

**Issue by daniMilio** [Lan2Play/eventula-manager#978]
We should have the option to turn the "none" Game option off in Admin, so that it is either displayed or not.

**Comment by Apfelwurm** [comment]
This are two seperate things, one is an enhancement to disable the "none" game, and the other one is a bug that should be fixed independent, therfore created https://github.com/Lan2Play/eventula-manager/issues/982.

**Comment by Apfelwurm** [comment]
fixed in dev with https://github.com/Lan2Play/eventula-manager/pull/1035 , will be in main in the next days :)
